# M7 HUB - Tema: blood
# ============================
# Roxo/magenta, combinando com o wallpaper Kaligator.

RED=$'\e[1;35m'
R=$'\e[0m'

# cores do "chip" powerline do usuário
CHIP_BG=$'\e[48;5;160m'   
CHIP_FG=$'\e[97m' 
        
ARROW_FG=$'\e[38;5;160m' 
ARROW_BG=$'\e[49m'

