# ============================
# M7 HUB - Tema: matrix
# ============================
# Verde, visual estilo terminal clássico/Matrix.

RED=$'\e[1;32m'
R=$'\e[0m'

# cores do "chip" powerline do usuário
CHIP_BG=$'\e[42m'
CHIP_FG=$'\e[30m'
ARROW_FG=$'\e[32m'
